import type { RateLimitMetadata } from "@http";

export type Context7ErrorOptions = {
  /** Machine-readable error code returned by Context7 or generated by the SDK. */
  code?: string;
  /** HTTP status code, when the request reached the Context7 API. */
  status?: number;
  /** Request identifier returned by the Context7 API. */
  requestId?: string;
  /** Rate-limit state returned with the failed request. */
  rateLimit?: RateLimitMetadata;
  /** Whether retrying the request may succeed. */
  retryable?: boolean;
  /** Original error that caused this error. */
  cause?: unknown;
};

export class Context7Error extends Error {
  public readonly code?: string;
  public readonly status?: number;
  public readonly requestId?: string;
  public readonly rateLimit?: RateLimitMetadata;
  public readonly retryable: boolean;
  public override readonly cause?: unknown;

  constructor(message: string, options: Context7ErrorOptions = {}) {
    super(message);
    this.name = "Context7Error";
    this.code = options.code;
    this.status = options.status;
    this.requestId = options.requestId;
    this.rateLimit = options.rateLimit;
    this.retryable = options.retryable ?? false;
    this.cause = options.cause;
  }
}
