#!/usr/bin/env tsx
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

const repoRoot = process.cwd();

type Transform = (body: string) => string;

interface SyncEntry {
  name: string;
  source: string;
  target: string;
  transform?: Transform;
}

// Each entry maps a canonical source file (typically under rules/ or skills/)
// to a generated plugin file. Add a new entry when another plugin needs to
// track a shared source. Keep the canonical file editable; the target is
// regenerated by `pnpm sync:plugins` and by the sync-plugins workflow.
const SYNCS: SyncEntry[] = [
  {
    name: "codex/context7 mcp skill",
    source: "rules/context7-mcp.md",
    target: "plugins/codex/context7/skills/context7/SKILL.md",
    transform: prependFrontmatter({
      name: "context7",
      description:
        "Use when the user asks about libraries, frameworks, SDKs, APIs, CLI tools, or cloud services. Activates for setup questions, configuration, version migrations, library-specific debugging, and code generation involving any framework (React, Next.js, Prisma, Supabase, Tailwind, Django, Spring Boot, etc.).",
    }),
  },
];

function prependFrontmatter(fields: Record<string, string | boolean>): Transform {
  const yaml = Object.entries(fields)
    .map(([k, v]) => `${k}: ${v}`)
    .join("\n");
  return (body) => `---\n${yaml}\n---\n\n${body}`;
}

const checkOnly = process.argv.includes("--check");
const drift: string[] = [];

for (const { name, source, target, transform } of SYNCS) {
  const sourcePath = resolve(repoRoot, source);
  const targetPath = resolve(repoRoot, target);
  const body = readFileSync(sourcePath, "utf8");
  const next = transform ? transform(body) : body;

  let current = "";
  try {
    current = readFileSync(targetPath, "utf8");
  } catch {}

  if (current === next) {
    console.log(`ok    ${name}`);
    continue;
  }

  if (checkOnly) {
    drift.push(name);
    console.error(`drift ${name} -> ${target}`);
    continue;
  }

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, next);
  console.log(`wrote ${name} -> ${target}`);
}

if (checkOnly && drift.length > 0) {
  console.error(`\n${drift.length} file(s) out of sync. Run: pnpm sync:plugins`);
  process.exit(1);
}
