#!/usr/bin/env tsx
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

const repoRoot = process.cwd();

type Transform = (body: string) => string;

interface SyncEntry {
  name: string;
  source: string;
  target: string;
  transform?: Transform;
}

// Each entry maps a canonical source file (under rules/ or skills/) to a
// generated plugin file. Add a new entry when another plugin needs to track
// a shared source. Keep canonical files editable; targets are regenerated by
// `pnpm sync:plugins` and by the sync-plugins workflow.
//
// - Raw copy (no transform): the target ends up byte-for-byte identical to
//   the source, including any YAML frontmatter the source already carries.
// - Transform: receives the source body and returns the target content.
//   Transforms can read other canonical files (e.g. to inherit a description
//   from a different skill) so frontmatter stays in lockstep with one place.
const SYNCS: SyncEntry[] = [
  {
    name: "claude context7-mcp skill",
    source: "skills/context7-mcp/SKILL.md",
    target: "plugins/claude/context7/skills/context7-mcp/SKILL.md",
  },
  {
    name: "cursor context7-mcp skill",
    source: "skills/context7-mcp/SKILL.md",
    target: "plugins/cursor/context7/skills/context7-mcp/SKILL.md",
  },
  {
    name: "codex context7-mcp skill",
    source: "rules/context7-mcp.md",
    target: "plugins/codex/context7/skills/context7-mcp/SKILL.md",
    transform: prependFrontmatterFromSkill("skills/context7-mcp/SKILL.md"),
  },
];

// Returns a transform that prepends the YAML frontmatter from another skill
// file. Used so the codex plugin's skill (whose body is the terse rule, not
// the long-form skill) still carries the canonical name + description.
function prependFrontmatterFromSkill(skillPath: string): Transform {
  return (body) => {
    const content = readFileSync(resolve(repoRoot, skillPath), "utf8");
    const match = content.match(/^---\n[\s\S]*?\n---\n/);
    if (!match) {
      throw new Error(`No YAML frontmatter found in ${skillPath}`);
    }
    return `${match[0]}\n${body}`;
  };
}

const checkOnly = process.argv.includes("--check");
const drift: string[] = [];

for (const { name, source, target, transform } of SYNCS) {
  const sourcePath = resolve(repoRoot, source);
  const targetPath = resolve(repoRoot, target);
  const body = readFileSync(sourcePath, "utf8");
  const next = transform ? transform(body) : body;

  let current = "";
  try {
    current = readFileSync(targetPath, "utf8");
  } catch {}

  if (current === next) {
    console.log(`ok    ${name}`);
    continue;
  }

  if (checkOnly) {
    drift.push(name);
    console.error(`drift ${name} -> ${target}`);
    continue;
  }

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, next);
  console.log(`wrote ${name} -> ${target}`);
}

if (checkOnly && drift.length > 0) {
  console.error(`\n${drift.length} file(s) out of sync. Run: pnpm sync:plugins`);
  process.exit(1);
}
